import { Inter } from "@next/font/google";
import Head from "next/head";
import Header from "../components/Header";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll z-0">
      <Head>
        <title>Learn NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="overflow-x-hidden">
        {/* HEADER */}
        <Header />
        {/* HERO */}

        <section id="hero" className="snap-center">
          <Hero />
        </section>

        {/* ABOUT */}
        {/* EXP */}
        {/* SKILLS */}
        {/* PROJECTS */}
        {/* CONTACT */}
      </main>
    </div>
  );
}
